question_data = [{"type": "boolean",
                  "difficulty": "easy",
                  "category": "Science: Computers",
                  "question": "Time on Computers is measured via the EPOX System.",
                  "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The open source program Redis is a relational database server.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "MacOS is based on Linux.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
                  "question": "DHCP stands for Dynamic Host Configuration Port.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "The &#039;Raspberry Pi&#039; series of single-board computers were created in the United States.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "Ada Lovelace is often considered the first computer programmer.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
                  "question": "RAM stands for Random Access Memory.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}
]
